# This file may be used to create an environment using:=
# $ conda create --name <env> --file <this file>=
# platform: osx-64=
brotli=1.1.0
brotli-bin=1.1.0
brotli-python=1.1.0
bzip2=1.0.8
ca-certificates=2023.11.17
cachecontrol=0.13.1
cachecontrol-with-filecache=0.13.1
causal-learn=0.1.3.7
certifi=2023.11.17
cffi=1.16.0
charset-normalizer=3.3.2
clarabel=0.6.0
cleo=2.1.0
colorama=0.4.6
contourpy=1.2.0
crashtest=0.4.1
cvxpy=1.4.1
cvxpy-base=1.4.1
cycler=0.12.1
cython=3.0.6
distlib=0.3.8
dowhy=0.10.1
dulwich=0.21.7
ecos=2.0.11
filelock=3.13.1
fonttools=4.46.0
freetype=2.12.1
gmp=6.3.0
gmpy2=2.1.2
idna=3.6
importlib-metadata=7.0.0
importlib_metadata=7.0.0
jaraco.classes=3.3.0
joblib=1.3.2
keyring=24.3.0
kiwisolver=1.4.5
lcms2=2.16
lerc=4.0.0
libblas=3.9.0
libbrotlicommon=1.1.0
libbrotlidec=1.1.0
libbrotlienc=1.1.0
libcblas=3.9.0
libcxx=16.0.6
libdeflate=1.19
libexpat=2.5.0
libffi=3.4.2
libgfortran=5.0.0
libgfortran5=13.2.0
libjpeg-turbo=3.0.0
liblapack=3.9.0
libopenblas=0.3.25
libosqp=0.6.3
libpng=1.6.39
libqdldl=0.1.5
libsqlite=3.44.2
libtiff=4.6.0
libwebp-base=1.3.2
libxcb=1.15
libzlib=1.2.13
llvm-openmp=17.0.6
matplotlib-base=3.8.2
more-itertools=10.1.0
mpc=1.3.1
mpfr=4.2.1
mpmath=1.3.0
msgpack-python=1.0.7
munkres=1.1.4
ncurses=6.4
networkx=3.2.1
numpy=1.26.2
openjpeg=2.5.0
openssl=3.2.0
osqp=0.6.3
packaging=23.2
pandas=2.1.4
patsy=0.5.4
pexpect=4.8.0
pillow=10.1.0
pip=23.3.1
pkginfo=1.9.6
platformdirs=3.11.0
poetry=1.7.1
poetry-core=1.8.1
poetry-plugin-export=1.6.0
pthread-stubs=0.4
ptyprocess=0.7.0
pycparser=2.21
pydot=1.4.2
pyparsing=3.1.1
pyproject_hooks=1.0.0
pysocks=1.7.1
python=3.11.6
python-build=1.0.3
python-dateutil=2.8.2
python-fastjsonschema=2.19.0
python-graphviz=0.20.1
python-installer=0.7.0
python-tzdata=2023.3
python_abi=3.11
pytz=2023.3.post1
qdldl-python=0.1.5.post2
rapidfuzz=3.5.2
readline=8.2
requests=2.31.0
requests-toolbelt=1.0.0
scikit-learn=1.3.2
scipy=1.11.4
scs=3.2.3
setuptools=68.2.2
shellingham=1.5.4
six=1.16.0
statsmodels=0.14.1
sympy=1.12
threadpoolctl=3.2.0
tk=8.6.13
tomli=2.0.1
tomlkit=0.12.3
tqdm=4.66.1
trove-classifiers=2023.11.29
typing-extensions=4.9.0
typing_extensions=4.9.0
tzdata=2023c
urllib3=2.1.0
virtualenv=20.25.0
wheel=0.42.0
xattr=0.10.1
xorg-libxau=1.0.11
xorg-libxdmcp=1.1.3
xz=5.2.6
zipp=3.17.0
zstd=1.5.5
